package com.example.notas.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val md_theme_light_primary = Color(0xFF00696E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6FF6FD)
val md_theme_light_onPrimaryContainer = Color(0xFF002021)
val md_theme_light_secondary = Color(0xFF4A6364)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8E9)
val md_theme_light_onSecondaryContainer = Color(0xFF041F21)
val md_theme_light_tertiary = Color(0xFFF9BB96)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0x5BF9BB96)
val md_theme_light_onTertiaryContainer = Color(0xFF321300)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFC)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFFAFDFC)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0x68DAE4E5)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4949)
val md_theme_light_outline = Color(0xFF6F7979)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inverseSurface = Color(0xFF2D3131)
val md_theme_light_inversePrimary = Color(0xFF4CD9E1)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00696E)
val md_theme_light_outlineVariant = Color(0xFFBEC8C9)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4CD9E1)
val md_theme_dark_onPrimary = Color(0xFF003739)
val md_theme_dark_primaryContainer = Color(0xFF004F53)
val md_theme_dark_onPrimaryContainer = Color(0xFF6FF6FD)
val md_theme_dark_secondary = Color(0xFFB1CCCD)
val md_theme_dark_onSecondary = Color(0xFF1B3436)
val md_theme_dark_secondaryContainer = Color(0xFF324B4C)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E9)
val md_theme_dark_tertiary = Color(0xFFFFB68A)
val md_theme_dark_onTertiary = Color(0xFF522300)
val md_theme_dark_tertiaryContainer = Color(0xFF743500)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBC8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1C)
val md_theme_dark_onBackground = Color(0xFFE0E3E3)
val md_theme_dark_surface = Color(0xFF191C1C)
val md_theme_dark_onSurface = Color(0xFFE0E3E3)
val md_theme_dark_surfaceVariant = Color(0xFF3F4949)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8C9)
val md_theme_dark_outline = Color(0xFF899393)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E3)
val md_theme_dark_inversePrimary = Color(0xFF00696E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4CD9E1)
val md_theme_dark_outlineVariant = Color(0xFF3F4949)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF89CFD3)
val container_Notas = Color(0x1DEDDD8C)
val Notas = Color(0xFFEDDD8C)
val light_Notas = Color(0xFF6C5E00)
val light_onNotas = Color(0xFFFFFFFF)
val light_NotasContainer = Color(0xFFFAE366)
val light_onNotasContainer = Color(0xFF211C00)
val dark_Notas = Color(0xFFDCC74D)
val dark_onNotas = Color(0xFF383000)
val dark_NotasContainer = Color(0xFF514700)
val dark_onNotasContainer = Color(0xFFFAE366)